version: "3"
services:
  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  nginx:
    depends_on:
      - web
    image: nginx:1.13.5-alpine
    ports:
      - "80:80"
      - "443:443"
volumes:
  mysql-data:

